### INTEL LICENSE STARTS BELOW
# INTEL CONFIDENTIAL
# Copyright (C) 2021-2022 Intel Corporation
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.
# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.
### INTEL LICENSE END
---
- name: Create test_dir directory
  ansible.windows.win_file:
    path: "{{ mssql_hammerdb.test_dir }}"
    state: directory

- name: Prepare autorunbuild.tcl
  ansible.windows.win_template:
    src: "mssql/autorunbuild.tcl.j2"
    dest: '{{ mssql_hammerdb.test_dir }}\autorunbuild.tcl'

- name: Prepare populate_db.bat
  ansible.windows.win_template:
    src: "mssql/populate_db.bat.j2"
    dest: '{{ hammerdb_bin_dir }}\populate_db.bat'

- name: Remove mssql_hammerdb.log
  ansible.windows.win_file:
    path: 'C:\Users\testadmin\AppData\Local\Temp\hammerdb.log'
    state: absent
  retries: 5
  delay: 10

- name: Run populate_db script with autorunbuild.tcl
  ansible.windows.win_shell: '.\populate_db.bat'
  args:
    chdir: "{{ hammerdb_bin_dir }}"
  async: 180000
  poll: 60
  no_log: true
  ignore_errors: true
  register: results

- name: Check if schema created correctly
  ansible.windows.win_shell: 'type C:\Users\testadmin\AppData\Local\Temp\hammerdb.log | find "SCHEMA COMPLETE"'
  register: is_schema_created
  failed_when:
    - is_schema_created.stdout == ""
