### INTEL LICENSE STARTS BELOW
# INTEL CONFIDENTIAL
# Copyright (C) 2021-2022 Intel Corporation
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.
# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.
### INTEL LICENSE END
---
hammerdb:
  install_path_prefix: "/opt"

mysql:
  root_pass: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') | default('' , True) }}"
  hammerdb_pass: "{{ lookup('env', 'MYSQL_HAMMERDB_PASSWORD') | default('', True) }}"
  default_mount_dir: "/var/lib"
  default_dir: "/var/lib/mysql"

mysql_conf:
  innodb_log_file_size: "{{ lookup('env', 'MYSQL_LOG_FILE_SIZE') | default('1024M', True) }}"
  innodb_buffer_pool_size: "{{ lookup('env', 'MYSQL_INNODB_BUFFER_POOL_SIZE') | default('67108864', True) }}"
  innodb_buffer_pool_instances: "{{ lookup('env', 'MYSQL_INNODB_BUFFER_POOL_INSTANCES') | default('16', True) }}"
  innodb_log_buffer_size: "{{ lookup('env', 'MYSQL_INNODB_LOG_BUFFER_SIZE') | default('64M', True) }}"
  innodb_doublewrite: "{{ lookup('env', 'MYSQL_INNODB_DOUBLEWRITE') | default('0', True) }}"
  innodb_thread_concurrency: "{{ lookup('env', 'MYSQL_INNODB_THREAD_CONCURRENCY') | default('0', True) }}"
  innodb_flush_log_at_trx_commit: "{{ lookup('env', 'MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT') | default('0', True) }}"
  innodb_max_dirty_pages_pct: "{{ lookup('env', 'MYSQL_INNODB_MAX_DIRTY_PAGES_PCT') | default('90', True) }}"
  innodb_max_dirty_pages_pct_lwm: "{{ lookup('env', 'MYSQL_INNODB_MAX_DIRTY_PAGES_PCT_LWM') | default('10', True) }}"
  join_buffer_size: "{{ lookup('env', 'MYSQL_JOIN_BUFFER_SIZE') | default('32K', True) }}"
  sort_buffer_size: "{{ lookup('env', 'MYSQL_SORT_BUFFER_SIZE') | default('32K', True) }}"
  innodb_use_native_aio: "{{ lookup('env', 'MYSQL_INNODB_USE_NATIVE_AIO') | default('1', True) }}"
  innodb_stats_persistent: "{{ lookup('env', 'MYSQL_INNODB_STATS_PERSISTENT') | default('1', True) }}"
  innodb_spin_wait_delay: "{{ lookup('env', 'MYSQL_INNODB_SPIN_WAIT_DELAY') | default('6', True) }}"
  innodb_max_purge_lag_delay: "{{ lookup('env', 'MYSQL_INNODB_MAX_PURGE_LAG_DELAY') | default('300000', True) }}"
  innodb_max_purge_lag: "{{ lookup('env', 'MYSQL_INNODB_MAX_PURGE_LAG') | default('0', True) }}"
  innodb_flush_method: "{{ lookup('env', 'MYSQL_INNODB_FLUSH_METHOD') | default('O_DIRECT_NO_FSYNC', True) }}"
  innodb_checksum_algorithm: "{{ lookup('env', 'MYSQL_INNODB_CHECKSUM_ALGORITHM') | default('none', True) }}"
  innodb_io_capacity: "{{ lookup('env', 'MYSQL_INNODB_IO_CAPACITY') | default('4000', True) }}"
  innodb_io_capacity_max: "{{ lookup('env', 'MYSQL_INNODB_IO_CAPACITY_MAX') | default('20000', True) }}"
  innodb_lru_scan_depth: "{{ lookup('env', 'MYSQL_INNODB_LRU_SCAN_DEPTH') | default('9000', True) }}"
  innodb_change_buffering: "{{ lookup('env', 'MYSQL_INNODB_CHANGE_BUFFERING') | default('none', True) }}"
  innodb_read_only: "{{ lookup('env', 'MYSQL_INNODB_READ_ONLY') | default('0', True) }}"
  innodb_page_cleaners: "{{ lookup('env', 'MYSQL_INNODB_PAGE_CLEANERS') | default('4', True) }}"
  innodb_undo_log_truncate: "{{ lookup('env', 'MYSQL_INNODB_UNDO_LOG_TRUNCATE') | default('off', True) }}"
  innodb_adaptive_flushing: "{{ lookup('env', 'MYSQL_INNODB_ADAPTIVE_FLUSHING') | default('1', True) }}"
  innodb_flush_neighbors: "{{ lookup('env', 'MYSQL_INNODB_FLUSH_NEIGHBORS') | default('0', True) }}"
  innodb_read_io_threads: "{{ lookup('env', 'MYSQL_INNODB_READ_IO_THREADS') | default('16', True) }}"
  innodb_write_io_threads: "{{ lookup('env', 'MYSQL_INNODB_WRITE_IO_THREADS') | default('16', True) }}"
  innodb_purge_threads: "{{ lookup('env', 'MYSQL_INNODB_PURGE_THREADS') | default('4', True) }}"
  innodb_adaptive_hash_index: "{{ lookup('env', 'MYSQL_INNODB_ADAPTIVE_HASH_INDEX') | default('0', True) }}"

mysql_listening_ip: "{{ hostvars['vm-database'].ansible_default_ipv4.address | default(hostvars['vm-database'].ansible_all_ipv4_addresses[0]) }}"

# Kernel parameters
sysctl_conf:
  kernel.sem: "250 32000 100 128"
  net.ipv4.ip_local_port_range: "9000 65500"
  net.core.rmem_default: 262144
  net.core.rmem_max: 4194304
  net.core.wmem_default: 262144
  net.core.wmem_max: 1048576
  fs.aio-max-nr: 1048576
  fs.file-max: 6815744

# Ephemeral and data disks configuration
disks_conf:
  - filesystem: ext4
    mountpoint: /mnt/ephemeraldata
    passno: 0
    options: "defaults"
    type: temp_disk
  - filesystem: xfs
    mountpoint: /mnt/mysqldata
    passno: 2
    options: "defaults,nofail,x-systemd.device-timeout=5"
    type: data_disk
