### INTEL LICENSE STARTS BELOW
# INTEL CONFIDENTIAL
# Copyright (C) 2021-2022 Intel Corporation
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.
# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.
### INTEL LICENSE END
---
- name: Clear hammerdb logs for {{ item }}
  ansible.builtin.file:
    path: /tmp/hammerdb.log
    state: absent

- name: Run hammerdb buildschema for {{ item }}
  ansible.builtin.command: bash -ilc "{{ hammerdb_install_path }}/hammerdbcli auto {{ hammerdb_install_path }}/schemabuild.tcl"
  args:
    chdir: "{{ hammerdb_install_path }}"
    creates: "/tmp/{{ item }}.hammerdb_schema_created"
  become: true
  become_user: oracle
  async: 180000
  poll: 60
  no_log: true
  register: schema_return
  changed_when:
    - schema_return.stdout != ""
    - '"skipped, since" not in schema_return.stdout'

- name: Copy hammerdb schema log
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: /tmp/hammerdb.log
    dest: /tmp/hammerdb-schema.log
  # prettier-ignore
  when: schema_return.changed   # noqa no-handler

- name: Fetch schema log as b64 to check schema completion
  ansible.builtin.slurp:
    src: /tmp/hammerdb-schema.log
  register: schema_log

- name: Save schema log as a fact
  ansible.builtin.set_fact:
    schema_log_contents: "{{ schema_log['content'] | b64decode }}"

- name: Fail if schema building failed
  ansible.builtin.fail:
    msg: "Schema building failed!"
  when: '"SCHEMA COMPLETE" not in schema_log_contents'

- name: Make hammerdb_schema_created file
  ansible.builtin.file:
    mode: "0644"
    path: "/tmp/{{ item }}.hammerdb_schema_created"
    state: touch
