### INTEL LICENSE STARTS BELOW
# INTEL CONFIDENTIAL
# Copyright (C) 2021-2022 Intel Corporation
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.
# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.
### INTEL LICENSE END
# @meta description: Documentation of Ansible part of Intel-OCS project.
# @tag installation # This tag indicates tasks that perform installations and configuration of neccessary components & tools.
# @tag experiments # This tag is related to tasks connected with benchmarking, i.e. preparing experiment running HammerDB and collecting results, metrics, etc.
---
# PREPARE AND DEPLOY

- name: Wait for connection and validate variables
  hosts: load_generator:sut
  gather_facts: false
  roles:
    - connection
    - validation
  tags: ["always"]

- name: Run common settings
  hosts: load_generator:sut
  roles:
    - common
  tags: ["always"]

- name: Setup disks, modify sysctl parameters, configure mysql
  hosts: sut
  roles:
    - disks
    - sysctl
    - mysql
  tags: ["installation"]

- name: Install hammerdb and build schema
  hosts: load_generator
  tasks:
    - name: Install hammerdb
      ansible.builtin.include_role:
        name: hammerdb
        tasks_from: mysql/configure.yaml
    - name: Build schema
      ansible.builtin.include_role:
        name: hammerdb
        tasks_from: mysql/build_schema.yaml
      loop: "{{ groups['sut'] }}"
  tags: ["installation"]

# RUN

- name: Benchmark start time
  hosts: localhost
  tasks:
    - name: Get benchmark start time
      ansible.builtin.set_fact:
        benchmark_start: "{{ now(utc=True).isoformat() }}"
        benchmark_directory_date: "{{ ansible_date_time['iso8601_basic_short']}}"
      changed_when: false
  tags: ["experiments"]

- name: Run hammerdb benchmark
  hosts: load_generator
  tasks:
    - name: Run hammerdb benchmark
      ansible.builtin.include_role:
        name: hammerdb
        tasks_from: mysql/run_benchmark.yaml
      loop: "{{ groups['sut'] }}"
  tags: ["experiments"]

- name: Benchmark end time
  hosts: localhost
  tasks:
    - name: Get benchmark end time
      ansible.builtin.set_fact:
        benchmark_end: "{{ now(utc=True).isoformat() }}"
      changed_when: false
    - name: Wait for metrics collection # pause is meant to give time for Azure metrics monitor to refresh (every 5 minutes)
      ansible.builtin.pause:
        minutes: 5
  tags: ["experiments"]

- name: Create benchmark report and metrics collection
  hosts: localhost
  connection: local
  roles:
    - parse_results
    - collect_metrics
  tags: ["experiments"]
