### INTEL LICENSE STARTS BELOW
# INTEL CONFIDENTIAL
# Copyright (C) 2021-2022 Intel Corporation
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.
# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.
### INTEL LICENSE END
# @meta description: Documentation of Ansible part of Intel-OCS project.
# @tag installation # This tag indicates tasks that perform installations and configuration of neccessary components & tools.
# @tag experiments # This tag is related to tasks connected with benchmarking, i.e. preparing experiment running HammerDB and collecting results, metrics, etc.
---
# PREPARE AND DEPLOY

- name: Wait for connection and validate variables
  hosts: load_generator:sut
  gather_facts: false
  vars:
    with_cloud_init: false
  roles:
    - connection
    - validation
  tags: ["always"]

- name: Setup disks, configure oracle
  hosts: sut
  roles:
    - disks
    - sysctl
    - oracle
  tags: ["installation"]

- name: Install hammerdb and build schema
  hosts: load_generator
  tasks:
    - name: Install hammerdb
      include_role:
        name: hammerdb
        tasks_from: oracle/configure.yaml
    - name: Build schema
      include_role:
        name: hammerdb
        tasks_from: oracle/build_schema.yaml
      loop: "{{ groups['sut'] }}"
  tags: ["installation"]

#RUN

- name: Benchmark start time
  hosts: localhost
  tasks:
    - name: Get benchmark start time
      set_fact:
        benchmark_start: "{{ now(utc=True).isoformat() }}"
        benchmark_directory_date: "{{ ansible_date_time['iso8601_basic_short']}}"
      changed_when: false
  tags: ["experiments"]

- name: Run hammerdb benchmark
  hosts: load_generator
  tasks:
    - name: Run hammerdb benchmark
      include_role:
        name: hammerdb
        tasks_from: oracle/run_benchmark.yaml
      loop: "{{ groups['sut'] }}"
  tags: ["experiments"]

- name: Benchmark end time
  hosts: localhost
  tasks:
    - name: Get benchmark end time
      set_fact:
        benchmark_end: "{{ now(utc=True).isoformat() }}"
      changed_when: false
    - name: Wait for metrics collection # pause is meant to give time for Azure metrics monitor to refresh (every 5 minutes)
      pause:
        minutes: 5
  tags: ["experiments"]

- name: Generate AWR report for database
  hosts: sut
  vars:
    awr_report: true
  roles:
    - oracle
  tags: ["experiments"]

- name: Create benchmark report and metrics collection
  hosts: localhost
  connection: local
  roles:
    - parse_results
    - collect_metrics
  tags: ["experiments"]
